name: binaries

on:
  workflow_dispatch:
  push:
    branches:
    tags:

jobs:
  build:
    name: Build go-flare with SLSA
    uses: ./.github/workflows/build-go-slsa3.yaml
    with:
      go_version: "${{ vars.GO_VERSION }}"
      ubuntu_version: "${{ vars.UBUNTU_VERSION }}"
      build_artifact_name: "avalanchego"

  build-verification:
    #if: github.ref_type == 'tag'
    name: Go Verification Build
    uses: ./.github/workflows/build-go-verification.yaml
    with:
      go_version: "${{ vars.GO_VERSION }}"
      ubuntu_version: "${{ vars.UBUNTU_VERSION }}"
      build_artifact_name: "avalanchego-verification"

  release:
    name: Release
    runs-on: "ubuntu-${{ vars.UBUNTU_VERSION }}"
    needs: [build, build-verification]
    #if: github.ref_type == 'tag'
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Install diffoscope
        run: sudo apt-get update -y && sudo apt-get install -y diffoscope-minimal
      
      - name: Install slsa-verifier
        uses: slsa-framework/slsa-verifier/actions/installer@v2.6.0
      
      - name: Install Cosign
        if: github.ref_type == 'tag'
        uses: sigstore/cosign-installer@v3.8.1

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          path: artifacts

      - name: Extract artifacts
        run: |
          mkdir -p release/

          mv artifacts/avalanchego-verification/avalanchego release/avalanchego-verification

          tar -xzf artifacts/avalanchego/folder.tgz -C artifacts/avalanchego/
          mv artifacts/avalanchego/binaries/avalanchego release/

          echo $(ls -la artifacts/)
          echo "---"
          echo $(ls -la artifacts/avalanchego-attestations)

          tar -xzf artifacts/avalanchego-attestations/folder.tgz -C artifacts/avalanchego-attestations/

          echo "---"
          echo $(ls -ls artifacts/avalanchego-attestations/)

          mv artifacts/avalanchego-attestations/*-slsa-attestations/avalanchego-binaries.build.slsa release/avalanchego.build.slsa


      - name: Verify reproducible build
        run: |
          HASH_MAIN=$(sha256sum release/avalanchego | awk '{print $1}')
          HASH_VERIFY=$(sha256sum release/avalanchego-verification | awk '{print $1}')
          
          if [ "$HASH_MAIN" = "$HASH_VERIFY" ]; then
            echo "Hashes match"
          else
            echo "Hashes don't match"

            diffoscope release/avalanchego release/avalanchego-verification || true
            
            exit 1
          fi

      - name: Verify SLSA provenance
        run: |
          slsa-verifier verify-artifact \
            release/avalanchego \
            --provenance-path release/avalanchego.build.slsa \
            --source-uri github.com/${{ github.repository }} \
            --builder-id https://github.com/${{ github.repository }}/.github/workflows/build-go-slsa3.yaml@refs/tags/${{ github.ref_name }}

#
      #- name: Package release
      #  run: |
      #    RELEASE_TAG="${{ github.ref_name }}"
      #    ARTIFACT_NAME="go-flare-${RELEASE_TAG}-linux-amd64.zip"
      #    
      #    cd artifacts/release
      #    zip -r ../../$ARTIFACT_NAME .
      #    
      #    echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
#
      #- name: Release
      #  uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      #  with:
      #    body: "TODO"
      #    files: |
      #      ${{ env.ARTIFACT_NAME }}
      #      *.intoto.jsonl